name: Deploy Secrets Workflow
on: push
jobs:
  deploy-secrets:
    name: Deploy Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Secrets
        env:
          CASE_STUDY_SECRET: ${{secrets.CASE_STUDY_SECRET}}
        run: |
            echo Secrets Deployed!